var objek = {};
objek.Name = 'Inggrid Suryani';
objek.Age = 23;
objek.Address = 'Jakarta, Indonesia';
objek.Hobbies = ["watch movies & anime", "play games", "read comics"];
objek.is_married = "no" == "yes";
objek.school = ["SMAN 43 Jakarta", "STMIK Nusa Mandiri Jakarta"];
objek.year_in = [2010, 2013];
objek.year_out = [2013, 2018];
objek.major = ["IPA", "S1 Teknik Informatika"];
objek.highschool = [school[0]," Year In: "+year_in[0], " Year Out: "+year_out[0], " Major: "+major[0]];
objek.college = [school[1]," Year In: "+year_in[1], " Year Out: "+year_out[1], " Major: "+major[1]];
objek.list_school = sma.join("|")+"||"+kuliah.join("|");
objek.skill_name = ["Microsoft Word", "Microsoft Excel", "Microsoft Power Point", "Coding"];
objek.level = ["Beginner", "Advanced", "Expert"];
objek.skills = skill_name[3] + " " + level[0];
objek.interest_in_coding = "yes" == "yes";
json = JSON.stringify(objek, '', '\t');
console.log(json);
